var dataVideo=[
{
	articleNumber:0,
	videoPlayerURL:"5836205007001",
	showVideoThum:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/Patricia-Florissi.png",
	cookieForLeadVideo:"ShowVideo_1",
	videoHead:"Innovate for the Future",
	videoDate:"30 April | 1:10:34",
	videoContent:"The Fourth Industrial Revolution is approaching and is, in many ways, already underway. While the full digital transformation will require new approaches to infrastructure, infrastructure management and security, there are several emerging technology trends already accelerating this shift. These technologies share a common thread: each of them is fueled by data. And as we continue to embrace the burgeoning digital economy, the true value of data as currency will become increasingly clear. Dell Technologies is here to empower organizations to embrace this world of change.",
	VideoDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/DELLEMCKB0006 DTF SGMY - Patricia Florissi - FINAL post.pdf",
	cookieForLead:"videoArticle_1",

	VideoSpeakerName1:"Patricia Florissi",
	VideoSpeakerDesc1:"Vice President, Global CTO for Sales and Distinguished Engineer, <br> Dell EMC",
	FBShareURL:"https://www.facebook.com/sharer/sharer.php?u=https%3A//www.delltechnologies.com/en-sg/events/forum/replay.htm",
	TwitterShareURL:"https://twitter.com/home?status=https%3A//www.delltechnologies.com/en-sg/events/forum/replay.htm",
	LinkedinShareURL:"https://www.linkedin.com/shareArticle?mini=true&url=https%3A//www.delltechnologies.com/en-sg/events/forum/replay.htm&title=&summary=&source=",

	
	relVidIconUrl1:"https://www.delltechnologies.com/ms-my/events/ai-summit.htm#lang=en&main=replay&secondary=dtw187440956",
	relVidIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
	relVidIconTitle1:"Video",
	relVidIconDecs1:"Unlock the power of data. Find out how artificial Intelligence extracts more value from data than ever before, impacting businesses, individuals and the way we live",
	relVidClicksCookie1:"clicksRelatedArticle_67",
	relVidIconUrl2:"",
	relVidIconImg2:"",
	relVidIconTitle2:"",
	relVidIconDecs2:"",
	relVidClicksCookie2:"",
	relVidIconUrl3:"",
	relVidIconImg3:"",
	relVidIconTitle3:"",
	relVidIconDecs3:"",
	relVidClicksCookie3:"",
	relVidIconUrl4:"",
	relVidIconImg4:"",
	relVidIconTitle4:"",
	relVidIconDecs4:"",
	relVidClicksCookie4:"",

	relVidThumb1:"pdfArticle_1",
	relVidThumbOverlay1:"pdf-doc-content",
	relVidThumbImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/keynote.jpg",
	relVidThumbDate1:"30 April | 1:10:34",
	relVidThumbDesc1:"The engines of human progress with Michael Dell and special guests.",
	relVidThumbSpeaker1:"Amit Midha",

	relVidThumb2:"video_0",
	relVidThumbOverlay2:"pdf-doc-content",
	relVidThumbImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/keynote.jpg",
	relVidThumbDate2:"30 April | 1:10:34",
	relVidThumbDesc2:"The engines of human progress with Michael Dell and special guests.",
	relVidThumbSpeaker2:"Amit Midha1"
},
{
	articleNumber:1,
	videoPlayerURL:"5836194428001",
	showVideoThum:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/Dune-Ives.png",
	cookieForLeadVideo:"ShowVideo_2",
	videoHead:"Creating a Wave of Change to Save Our Ocean",
	videoDate:"30 April | 1:10:34",
	videoContent:"Dr. Dune Ives, Executive Director of the award-winning Lonely Whale and Managing Director of NextWave Plastics will share with the audience the history of the Lonely Whale, a real creature that inspired the launch of the non-profit organization by the same name and continues to drive Dune and her team's focus on Radical Collaboration to save our ocean from plastic pollution. Dr. Ives will present Lonely Whale's perspective on plastic pollution and why market-driven initiatives including NextWave Plastics are so critical to create change at the scale needed to save our ocean from marine litter. Highlighted throughout the presentation is the leadership already demonstrated by companies in the South Asian region that can serve as models for others to follow. Dr. Ives will close the presentation by presenting opportunities for corporations and individuals to further positively impact the state of ocean health.",
	VideoDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/3.1%20Guest%20Keynote%20Creating%20a%20Wave%20of%20Change%20to%20Save%20Our%20Ocean_Dune%20Ives_FINAL.pdf",
	cookieForLead:"videoArticle_2",

	VideoSpeakerName1:"Dune Ives ",
	VideoSpeakerDesc1:"Executive Director, Lonely Whale ",

	FBShareURL:"https://www.facebook.com/sharer/sharer.php?u=https%3A//www.delltechnologies.com/en-sg/events/forum/replay.htm",
	TwitterShareURL:"https://twitter.com/home?status=https%3A//www.delltechnologies.com/en-sg/events/forum/replay.htm",
	LinkedinShareURL:"https://www.linkedin.com/shareArticle?mini=true&url=https%3A//www.delltechnologies.com/en-sg/events/forum/replay.htm&title=&summary=&source=",

	relVidIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
	relVidIconTitle1:"WhitePaper",
	relVidIconDecs1:"The engines of human progress with Michael",

	relVidIconUrl2:"",
	relVidIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon22.jpg",
	relVidIconTitle2:"Infographic",
	relVidIconDecs2:"The engines of human progress with Michael",

	relVidIconUrl3:"",
	relVidIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon33.jpg",
	relVidIconTitle3:"Weblink",
	relVidIconDecs3:"The engines of human progress with Michael",

	relVidIconUrl4:"",
	relVidIconImg4:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
	relVidIconTitle4:"Whitepaper",
	relVidIconDecs4:"The engines of human progress with Michael",

	relVidThumb1:"pdfArticle_1",
	relVidThumbOverlay1:"pdf-doc-content",
	relVidThumbImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/keynote.jpg",
	relVidThumbDate1:"30 April | 1:10:34",
	relVidThumbDesc1:"The engines of human progress with Michael Dell and special guests.",
	relVidThumbSpeaker1:"Amit Midha",

	relVidThumb2:"video_0",
	relVidThumbOverlay2:"pdf-doc-content",
	relVidThumbImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/keynote.jpg",
	relVidThumbDate2:"30 April | 1:10:34",
	relVidThumbDesc2:"The engines of human progress with Michael Dell and special guests.",
	relVidThumbSpeaker2:"Amit Midha2"
},
{
	articleNumber:2,
	videoPlayerURL:"5972540951001",
	showVideoThum:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/AmitMidha.png",
	cookieForLeadVideo:"ShowVideo_3",
	videoHead:"Keynote - Innovate Today & Customer Case Study - KPMG",
	videoDate:"30 April | 1:10:34",
	videoContent:"This session covers the phenomenon of digital transformation as a driving force for IT, workforce and security transformations in today's organizations. Dell Technologies portfolio is optimized to assist our customers get the most out of their transformation's experiences. We will illustrate how our customers have leveraged our portfolio to achieve significant business results through reinvention of their legacy businesses, optimization of productivity, and new courses they set for their businesses with ongoing focus on innovation. The session will also cover how success hinges on business becoming more intelligent by leveraging their data and emerging technologies.",
	VideoDownload:"",
	cookieForLead:"videoArticle_3",

	VideoSpeakerName1:"Amit Midha",
	VideoSpeakerDesc1:"President Commercial Business, Asia Pacific and Japan,<br>Dell EMC",

	VideoSpeakerName2:"Lyon Poh",
	VideoSpeakerDesc2:"Head of Digital, Innovation Leader, Chief Information Officer,<br>KPMG",

	FBShareURL:"https://www.facebook.com/sharer/sharer.php?u=https%3A//www.delltechnologies.com/en-sg/events/forum/replay.htm",
	TwitterShareURL:"https://twitter.com/home?status=https%3A//www.delltechnologies.com/en-sg/events/forum/replay.htm",
	LinkedinShareURL:"https://www.linkedin.com/shareArticle?mini=true&url=https%3A//www.delltechnologies.com/en-sg/events/forum/replay.htm&title=&summary=&source=",

	relVidIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
	relVidIconTitle1:"WhitePaper",
	relVidIconDecs1:"The engines of human progress with Michael",

	relVidIconUrl2:"",
	relVidIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon22.jpg",
	relVidIconTitle2:"Infographic",
	relVidIconDecs2:"The engines of human progress with Michael",

	relVidIconUrl3:"",
	relVidIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon33.jpg",
	relVidIconTitle3:"Weblink",
	relVidIconDecs3:"The engines of human progress with Michael",

	relVidIconUrl4:"",
	relVidIconImg4:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
	relVidIconTitle4:"Whitepaper",
	relVidIconDecs4:"The engines of human progress with Michael",

	relVidThumb1:"pdfArticle_1",
	relVidThumbOverlay1:"pdf-doc-content",
	relVidThumbImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/keynote.jpg",
	relVidThumbDate1:"30 April | 1:10:34",
	relVidThumbDesc1:"The engines of human progress with Michael Dell and special guests.",
	relVidThumbSpeaker1:"Amit Midha",

	relVidThumb2:"video_0",
	relVidThumbOverlay2:"pdf-doc-content",
	relVidThumbImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/keynote.jpg",
	relVidThumbDate2:"30 April | 1:10:34",
	relVidThumbDesc2:"The engines of human progress with Michael Dell and special guests.",
	relVidThumbSpeaker2:"Amit Midha2"
}
];

var dataArticle=[
	{
		articleNumber:0,

		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",

		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Kishor-Bhagwat.png",
		artSpeakerName1:"Kishor Bhagwat",
		artSpeakerDecs1:"Director – Cloud Platform Specialists (APJ),<br>Dell EMC",

		artSpeakerUrl2:"",
		artSpeakerName2:"",
		artSpeakerDecs2:"",

		artCat:"IT Transformation",
		artMainHead:"The Dell Technologies Multi-Cloud Strategy:  On Prem, Off Prem or Public or Private. How do you choose?",
		artDate:"30 April | 1:10:34",
		artMainContent:"Public, private, on premises, off premises. Do one or all of these provide what you need? Dell Technologies can help solve the challenges of Multi-Cloud and what it can mean for your business. This session will help you decipher what Cloud really can mean for you.",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/The Dell Technologies Multi-Cloud Strategy.pdf",
		cookieForLead:"pdfArticleLead_1",

		relArtIconUrl1:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/automated-it-service-delivery-drives-it-transformation-and-business-value.pdf",
		relArtIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle1:"ESG Report",
		relArtIconDecs1:"Automated IT Service Delivery Drives ITT Brief",
		relArtClicksCookie1:"clicksRelatedArticle_1",

		relArtIconUrl2:"http://www.emc.com/video-collateral/demos/microsites/mediaplayer-video/bank-leumi-digital-transformation.htm",
		relArtIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon33.jpg",
		relArtIconTitle2:"Video",
		relArtIconDecs2:"Bank Leumi adding real value with Dell EMC's Hybrid Cloud",
		relArtClicksCookie2:"clicksRelatedArticle_2",

		relArtIconUrl3:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/esg-in-cloud-data-protection-wp.pdf",
		relArtIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle3:"Third Party Report",
		relArtIconDecs3:"ESG: Economic Value of In-Cloud Data Protection with Dell EMC Data Protection Software",
		relArtClicksCookie3:"clicksRelatedArticle_3",

		relArtIconUrl4:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/esg-transform-your-it-with-modern-server-infrastucture-brief.pdf",
		relArtIconImg4:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle4:"ESG Report",
		relArtIconDecs4:"Transform IT with Modern Server Infrastructure Brief",
		relArtClicksCookie4:"clicksRelatedArticle_4",

		relArtThumb1:"pdfArticle_1",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/2018/Chin.png",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:"The Power of the Compute Portfolio: Dell EMC PowerEdge",
		relArtThumbSpeaker1:"Chin Boon Ping",

		relArtThumb2:"pdfArticle_2",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Matthew-Zwolenski.png",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:"Make it Real - Modernize your IT Infrastructure with Dell EMC",
		relArtThumbSpeaker2:"Matthew Zwolenski"
	},
	{
		articleNumber:1,

		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",

		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/2018/Chin.png",
		artSpeakerName1:"Chin Boon Ping",
		artSpeakerDecs1:"Business Manager, GCN (Global Compute & Networking),<br>Dell EMC",

		artSpeakerUrl2:"",
		artSpeakerName2:"",
		artSpeakerDecs2:"",

		artCat:"IT Transformation",
		artMainHead:"The Power of the Compute Portfolio: Dell EMC PowerEdge",
		artDate:"30 April | 1:10:34",
		artMainContent:"Transforming IT can speed application deployment, reduce your effort on IT operations, and reduce costs.  PowerEdge is the bedrock of modern IT. Learn how our customers are using PowerEdge to power their applications now and in the future.",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/The Power of the Compute Portfolio Dell EMC PowerEdge.pdf",
		cookieForLead:"pdfArticleLead_2",

		relArtIconUrl1:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/esg-transform-your-it-with-modern-server-infrastucture-brief.pdf",
		relArtIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle1:"ESG Report",
		relArtIconDecs1:"Transform IT with Modern Server Infrastructure Brief",
		relArtClicksCookie1:"clicksRelatedArticle_4",

		relArtIconUrl2:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/dellemc-cyber-resilient-architecture-poweredge.pdf",
		relArtIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle2:"Third Party Report",
		relArtIconDecs2:"EMA-Dell EMC PowerEdge Servers- Investing in a Cyber-Resilient Architecture",
		relArtClicksCookie2:"clicksRelatedArticle_5",

		relArtIconUrl3:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/the-5-surprising-ways-server-technology-is-advancing-sds.pdf",
		relArtIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle3:"Brochure",
		relArtIconDecs3:"The 5 Surprising Ways Server Technology is Advancing SDS",
		relArtClicksCookie3:"clicksRelatedArticle_6",

		relArtIconUrl4:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/esg-networking-role-in-it-transformation.pdf",
		relArtIconImg4:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle4:"ESG Report",
		relArtIconDecs4:"ITT Maturity & SDN: ESG The Network’s Role in IT Transformation",
		relArtClicksCookie4:"clicksRelatedArticle_7",

		relArtThumb1:"pdfArticle_2",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Matthew-Zwolenski.png",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:"Make it Real - Modernize your IT Infrastructure with Dell EMC",
		relArtThumbSpeaker1:"Matthew Zwolenski",

		relArtThumb2:"pdfArticle_3",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"https://www.delltechnologies.com/content/dam/delltechnologies/images/forum/YonasSeme.jpg",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:"The Power of Connectivity: The Dell EMC Networking Portfolio",
		relArtThumbSpeaker2:"Yonas Seme"
	},
		
	{
		articleNumber:2,
		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",
		
		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Matthew-Zwolenski.png",
		artSpeakerName1:"Matthew Zwolenski",
		artSpeakerDecs1:"Vice President, Commercial Presales, Asia Pacific and Japan,<br>Dell EMC",
		
		artSpeakerUrl2:"",
		artSpeakerName2:"",
		artSpeakerDecs2:"",
		
		artCat:"IT Transformation",
		artMainHead:"Make it Real - Modernize your IT Infrastructure with Dell EMC",
		artDate:"30 April | 1:10:34",
		artMainContent:"The benefits of IT transformation are real. Did you know that you are  2X more likely to exceed revenue goals and allocate up to an incremental 12% of annual IT spend on Innovation through IT Transformation. Learn about the Dell EMC Infrastructure Solutions and how they can help you transform your IT and put you on a path to Digital Transformation",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/Make it Real - Modernize your IT Infrastructure with Dell EMC.pdf",
		cookieForLead:"pdfArticleLead_3",

		relArtIconUrl1:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/esg-networking-role-in-it-transformation.pdf",
		relArtIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle1:"ESG Report",
		relArtIconDecs1:"ITT Maturity & SDN: ESG The Network’s Role in IT Transformation",
		relArtClicksCookie1:"clicksRelatedArticle_7",

		relArtIconUrl2:"https://www.dellemc.com/en-sg/converged-infrastructure/index.htm#cobrand=xeon&video-overlay=5743076379001",
		relArtIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",relArtIconTitle2:"Video",
		relArtIconDecs2:"Customer Reference: Johnsonville, LLC",
		relArtClicksCookie2:"clicksRelatedArticle_8",
		
		relArtIconUrl3:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/h15779-business-critical-apps-vxrail.pdf",
		relArtIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle3:"Whitepaper",
		relArtIconDecs3:"Business Critical Apps on VxRail",
		relArtClicksCookie3:"clicksRelatedArticle_9",
		
		relArtIconUrl4:"https://www.dellemc.com/en-sg/converged-infrastructure/hci-infographic.htm",
		relArtIconImg4:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon22.jpg",
		relArtIconTitle4:"Animated Infographic",
		relArtIconDecs4:"The Business Value of Transforming IT Through HCI",
		relArtClicksCookie4:"clicksRelatedArticle_10",
		
		relArtThumb1:"pdfArticle_3",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/delltechnologies/images/forum/YonasSeme.jpg",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:"The Power of Connectivity: The Dell EMC Networking Portfolio",
		relArtThumbSpeaker1:"Yonas Seme",
		
		relArtThumb2:"pdfArticle_4",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Matthew-Oostven---photo.png",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:"The Power of Convergence: The Dell EMC Converged and Hyper Converged Portfolio",
		relArtThumbSpeaker2:"Matthew Oostveen"
	},
	{
		articleNumber:3,
		
		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",
		
		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/delltechnologies/images/forum/YonasSeme.jpg",
		artSpeakerName1:"Yonas Seme",
		artSpeakerDecs1:"Director,<br>APJC Server & Networking CoC",
		
		artSpeakerUrl2:"",
		artSpeakerName2:"",
		artSpeakerDecs2:"",
		
		artCat:"IT Transformation",
		artMainHead:"The Power of Connectivity: The Dell EMC Networking Portfolio",
		artDate:"30 April | 1:10:34",
		artMainContent:"Ethernet, Fiber Channel or Software Defined Networking, which is the right choice for you? This session will present the various Dell EMC Networking options and provide you will a complete overview of our networking offerings.",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/The Power of Connectivity The Dell EMC Networking Portfolio.pdf",
		cookieForLead:"pdfArticleLead_4",

		relArtIconUrl1:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/esg-networking-role-in-it-transformation.pdf",
		relArtIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle1:"ESG Report",
		relArtIconDecs1:"ITT Maturity & SDN: ESG The Network’s Role in IT Transformation",
		relArtClicksCookie1:"clicksRelatedArticle_7",
		
		relArtIconUrl2:"https://www.emc.com/video-collateral/demos/microsites/mediaplayer-video/dellemc-esg-networking-itt.htm",
		relArtIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon33.jpg",
		relArtIconTitle2:"Video",
		relArtIconDecs2:"The Network's Foundational Role in IT Transformation",
		relArtClicksCookie2:"clicksRelatedArticle_8",
		
		relArtIconUrl3:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/h15779-business-critical-apps-vxrail.pdf",
		relArtIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle3:"Whitepaper",
		relArtIconDecs3:"Business Critical Apps on VxRail",
		relArtClicksCookie3:"clicksRelatedArticle_9",
		
		relArtIconUrl4:"https://www.dellemc.com/en-sg/converged-infrastructure/hci-infographic.htm",
		relArtIconImg4:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon22.jpg",
		relArtIconTitle4:"Animated Infographic",
		relArtIconDecs4:"The Business Value of Transforming IT Through HCI",
		relArtClicksCookie4:"clicksRelatedArticle_10",
		
		relArtThumb1:"pdfArticle_4",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Matthew-Oostven---photo.png",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:"The Power of Convergence: The Dell EMC Converged and Hyper Converged Portfolio",
		relArtThumbSpeaker1:"Matthew Oostveen",
		
		relArtThumb2:"pdfArticle_5",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Amit-Sharma.png",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:"Dell EMC High-End Storage: What's New in PowerMax & XtremIO X2",
		relArtThumbSpeaker2:"Amit Sharma"
	},
	{
		articleNumber:4,
		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",
		
		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Matthew-Oostven---photo.png",
		artSpeakerName1:"Matthew Oostveen",
		artSpeakerDecs1:"Modern Data Centre Chief Technology Officer, Asia Pacific and Japan,<br>Dell EMC",
		
		artSpeakerUrl2:"",
		artSpeakerName2:"",
		artSpeakerDecs2:"",
		
		artCat:"IT Transformation",
		artMainHead:"The Power of Convergence: The Dell EMC Converged and Hyper Converged Portfolio",
		artDate:"30 April | 1:10:34",
		artMainContent:"Converged and Hyper-Converged systems are the fastest way to achieve business outcomes. In this session, you will learn about how Dell EMC's converged and hyper-converged portfolio, including VxRail, VxRack and VxBlock 1000, has evolved to support the requirements of modern data centers around the world.",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/The Power of Convergence The Dell EMC Converged and Hyper Converged Portfolio.pdf",
		cookieForLead:"pdfArticleLead_5",

		relArtIconUrl1:"https://www.dellemc.com/en-sg/converged-infrastructure/index.htm#cobrand=xeon&video-overlay=5743076379001",
		relArtIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon33.jpg",
		relArtIconTitle1:"Video",
		relArtIconDecs1:"Customer Reference: Johnsonville, LLC",
		relArtClicksCookie1:"clicksRelatedArticle_8",
		
		relArtIconUrl2:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/h15779-business-critical-apps-vxrail.pdf",
		relArtIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle2:"Whitepaper",
		relArtIconDecs2:"Business Critical Apps on VxRail",
		relArtClicksCookie2:"clicksRelatedArticle_9",
		
		relArtIconUrl3:"https://www.dellemc.com/en-sg/converged-infrastructure/hci-infographic.htm",
		relArtIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon22.jpg",relArtIconTitle3:"Animated Infographic",
		relArtIconDecs3:"The Business Value of Transforming IT Through HCI",
		relArtClicksCookie3:"clicksRelatedArticle_10",
		
		relArtIconUrl4:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/idc-nvme-unlocking-next-gen-tier-0-data-storage.pdf",
		relArtIconImg4:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle4:"Third Party Report",
		relArtIconDecs4:"IDC - PowerMax NVMe Whitepaper",
		relArtClicksCookie4:"clicksRelatedArticle_11",
		
		relArtThumb1:"pdfArticle_5",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Amit-Sharma.png",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:"Dell EMC High-End Storage: What's New in PowerMax & XtremIO X2",
		relArtThumbSpeaker1:"Amit Sharma",
		
		relArtThumb2:"pdfArticle_6",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Simon-Low.png",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:"Dell EMC Unity & SC Series: Midrange Storage Portfolio Overview",
		relArtThumbSpeaker2:"Simon Low"
	},
	{
		articleNumber:5,
		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",
		
		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Amit-Sharma.png",
		artSpeakerName1:"Amit Sharma",
		artSpeakerDecs1:"Senior Manager, Modern Data Center Team, South Asia,<br>Dell EMC",
		
		artSpeakerUrl2:"",
		artSpeakerName2:"",
		artSpeakerDecs2:"",
		
		artCat:"IT Transformation",
		artMainHead:"Dell EMC High-End Storage: What’s New in PowerMax & XtremIO X2",
		artDate:"30 April | 1:10:34",
		artMainContent:"Come learn all about what's new in Dell EMC High-End Storage. The new Dell EMC PowerMax, the world's fastest array, is the most recent addition to our industry-leading portfolio. PowerMax is built on the core proven enterprise features of VMAX while also delivering unprecedented performance via NVMe technology and automated data placement for maximum performance with a built-in machine learning engine. The session will also cover XtremIO X2, the purpose-built All-Flash array with a metadata-centric architecture, continuing to deliver more performance, capacity, data services and simplicity. XtremIO's unique metadata-aware native replication will be a cornerstone for this session.",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/Dell EMC High-End Storage What’s New in PowerMax & XtremIO X2.pdf",
		cookieForLead:"pdfArticleLead_6",

		relArtIconUrl1:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/idc-nvme-unlocking-next-gen-tier-0-data-storage.pdf",
		relArtIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle1:"Third Party Report",
		relArtIconDecs1:"IDC - PowerMax NVMe Whitepaper",
		relArtClicksCookie1:"clicksRelatedArticle_11",
		
		relArtIconUrl2:"https://www.dellemc.com/en-us/storage/powermax.htm#collapse&video-overlay=5773299265001",
		relArtIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon33.jpg",
		relArtIconTitle2:"Video",
		relArtIconDecs2:"PowerMax Animated Overview Video",
		relArtClicksCookie2:"clicksRelatedArticle_12",
		
		relArtIconUrl3:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/h15839-dellemc-5-reasons-to-choose-vmax-af-storage.pdf",
		relArtIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon22.jpg",
		relArtIconTitle3:"Infographic",
		relArtIconDecs3:"PowerMax Animated Infographic",
		relArtClicksCookie3:"clicksRelatedArticle_13",
		
		relArtIconUrl4:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/midrange-customers-demand-high-end-functionality-at-affordable-prices.pdf",
		relArtIconImg4:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle4:"Third Party Report",
		relArtIconDecs4:"IDC - Midrange Storage Whitepaper",
		relArtClicksCookie4:"clicksRelatedArticle_14",
		
		relArtThumb1:"pdfArticle_6",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Simon-Low.png",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:"Dell EMC Unity & SC Series: Midrange Storage Portfolio Overview",
		relArtThumbSpeaker1:"Simon Low",
		
		relArtThumb2:"pdfArticle_0",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Kishor-Bhagwat.png",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:"The Dell Technologies Multi-Cloud Strategy:  On Prem, Off Prem or Public or Private. How do you choose?",
		relArtThumbSpeaker2:"Kishor Bhagwat"
	},
	{
		articleNumber:6,
		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",
		
		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Simon-Low.png",
		artSpeakerName1:"Simon Low",
		artSpeakerDecs1:"Senior SE Primary Storage | Modern Data Center Team(MDC)",
		
		artSpeakerUrl2:"",
		artSpeakerName2:"",
		artSpeakerDecs2:"",
		
		artCat:"IT Transformation",
		artMainHead:"Dell EMC Unity & SC Series: Midrange Storage Portfolio Overview",
		artDate:"30 April | 1:10:34",
		artMainContent:"Go anywhere with the modern, reliable Dell EMC's Midrange storage portfolio. This session provides an overview of our flagship Dell EMC & SC Series solutions. Both are flexible, rich in features and very affordable. Come hear and see what's new.",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/Dell EMC Unity & SC Series Midrange Storage Portfolio Overview.pdf",
		cookieForLead:"pdfArticleLead_7",

		relArtIconUrl1:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/midrange-customers-demand-high-end-functionality-at-affordable-prices.pdf",
		relArtIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",relArtIconTitle1:"Third Party Report",
		relArtIconDecs1:"IDC - Midrange Storage Whitepaper",
		relArtClicksCookie1:"clicksRelatedArticle_14",
		
		relArtIconUrl2:"https://www.dellemc.com/en-us/storage/unity.htm#cobrand=xeon&video-overlay=5276994924001&collapse",
		relArtIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon33.jpg",
		relArtIconTitle2:"Video",
		relArtIconDecs2:"Dell EMC Unity + CloudIQ Animated Video",
		relArtClicksCookie2:"clicksRelatedArticle_15",
		
		relArtIconUrl3:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/dellemc-scseries-accelerate-workloads-automate-savings.pdf",
		relArtIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon22.jpg",
		relArtIconTitle3:"Infographic",
		relArtIconDecs3:"SC Series Family Infographic",
		relArtClicksCookie3:"clicksRelatedArticle_16",
		
		relArtIconUrl4:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/automated-it-service-delivery-drives-it-transformation-and-business-value.pdf",
		relArtIconImg4:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle4:"ESG Report",
		relArtIconDecs4:"Automated IT Service Delivery Drives ITT Brief",
		relArtClicksCookie4:"clicksRelatedArticle_1",
		
		relArtThumb1:"pdfArticle_0",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Kishor-Bhagwat.png",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:"The Dell Technologies Multi-Cloud Strategy:  On Prem, Off Prem or Public or Private. How do you choose?",
		relArtThumbSpeaker1:"Kishor Bhagwat",
		
		relArtThumb2:"pdfArticle_1",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/2018/Chin.png",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:"The Power of the Compute Portfolio: Dell EMC PowerEdge",
		relArtThumbSpeaker2:"Chin Boon Ping"
	},	
	{
		articleNumber:7,
		
		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",
		
		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Vish-Phaneendra.jpg",
		artSpeakerName1:"Vish Phaneendra",
		artSpeakerDecs1:"Director, South Asia,<br>Pivotal",
		
		artSpeakerUrl2:"",
		artSpeakerName2:"",
		artSpeakerDecs2:"",
		
		artCat:"Digital Transformation",
		artMainHead:"Introduction to Pivotal Software",
		artDate:"30 April | 1:10:34",
		artMainContent:"It's said that 'speed to market' is the only remaining competitive advantage. But it's not just about going fast. It's about building the right things for your customers. Pivotal offers the platform, tools, and methodologies that help the world's most important companies deliver exceptional user experiences. Join us to hear all about what it takes to transform how you build, deploy and run software.",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/Introduction to Pivotal Software.pdf",
		cookieForLead:"pdfArticleLead_8",

		relArtIconUrl1:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/forrester-8-steps-cios-must-take-to-transform-with-artificial-intelligence.pdf",
		relArtIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle1:"Forrester",
		relArtIconDecs1:"8 Steps CIOs Must Take to Transform with AI",
		relArtClicksCookie1:"clicksRelatedArticle_17",

		relArtIconUrl2:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/forbes-insights-artificially-intelligent-data-centers.pdf",
		relArtIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle2:"Third Party Report",
		relArtIconDecs2:"Forbes insights- Artificially Intelligent Data Centers-How the C-Suite Is Embracing Continuous Change to Drive Value",
		relArtClicksCookie2:"clicksRelatedArticle_18",

		relArtIconUrl3:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/practitioner-guide-to-artificial-intelligence.pdf",
		relArtIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle3:"Third Party Report",
		relArtIconDecs3:"Moor Insights - A Practitioners Guide To Artificial Intelligence",
		relArtClicksCookie3:"clicksRelatedArticle_19",

		relArtIconUrl4:"",
		relArtIconImg4:"",
		relArtIconTitle4:"",
		relArtIconDecs4:"",
		relArtClicksCookie4:"",
		
		relArtThumb1:"pdfArticle_8",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/delltechnologies/images/forum/Andrew%20Haschka%20-Updated.jpg",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:"Building a Foundation ​for Digital Business​",
		relArtThumbSpeaker1:"Andrew Haschka",
		
		relArtThumb2:"pdfArticle_9",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/2018/Romain-Bottier.png",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:"Why Artificial Intelligence & Data Analytics Is Essential For Your Business",
		relArtThumbSpeaker2:"Romain Bottier"
	},
	{
		articleNumber:8,
		
		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",
		
		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/delltechnologies/images/forum/Andrew%20Haschka%20-Updated.jpg",
		artSpeakerName1:"Andrew Haschka",
		artSpeakerDecs1:"Director,<br>VMware Cloud Platform Asia Pacific and Japan",
		
		artSpeakerUrl2:"",
		artSpeakerName2:"",
		artSpeakerDecs2:"",
		
		artCat:"Digital Transformation",
		artMainHead:"Building a Foundation ​for Digital Business​",
		artDate:"30 April | 1:10:34",
		artMainContent:"The journey of transformation is unique to every organization but complex for all. VMware streamlines the journey to digital business by unlocking value from today’s technologies while enabling the integration of tomorrow’s. Join us to hear more about how VMware compute, cloud, mobility, networking, and security software forms a dynamic, consistent digital foundation to deliver the apps that power business innovation.",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/Building%20a%20Foundation%20%E2%80%8Bfor%20Digital%20Business%E2%80%8B.pdf",
		cookieForLead:"pdfArticleLead_9",

		relArtIconUrl1:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/forrester-8-steps-cios-must-take-to-transform-with-artificial-intelligence.pdf",
		relArtIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle1:"Forrester",
		relArtIconDecs1:"8 Steps CIOs Must Take to Transform with AI",
		relArtClicksCookie1:"clicksRelatedArticle_17",

		relArtIconUrl2:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/forbes-insights-artificially-intelligent-data-centers.pdf",
		relArtIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle2:"Third Party Report",
		relArtIconDecs2:"Forbes insights- Artificially Intelligent Data Centers-How the C-Suite Is Embracing Continuous Change to Drive Value",
		relArtClicksCookie2:"clicksRelatedArticle_18",

		relArtIconUrl3:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/practitioner-guide-to-artificial-intelligence.pdf",
		relArtIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle3:"Third Party Report",
		relArtIconDecs3:"Moor Insights - A Practitioners Guide To Artificial Intelligence",
		relArtClicksCookie3:"clicksRelatedArticle_19",

		relArtIconUrl4:"",
		relArtIconImg4:"",
		relArtIconTitle4:"",
		relArtIconDecs4:"",
		relArtClicksCookie4:"",
		
		relArtThumb1:"pdfArticle_9",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/2018/Romain-Bottier.png",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:"Why Artificial Intelligence & Data Analytics Is Essential For Your Business",
		relArtThumbSpeaker1:"Romain Bottier",
		
		relArtThumb2:"pdfArticle_10",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/2018/Colin-Pont.png",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:"Building the Connected Business powered by  Dell Boomi",
		relArtThumbSpeaker2:"Colin Pont"
	},
	{
		articleNumber:9,
		
		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",
		
		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/2018/Romain-Bottier.png",
		artSpeakerName1:"Romain Bottier",
		artSpeakerDecs1:"Subject Matter Expert – HPC & AI,<br>Dell EMC",
		
		artSpeakerUrl2:"",
		artSpeakerName2:"",
		artSpeakerDecs2:"",
		
		artCat:"Digital Transformation",
		artMainHead:"Why Artificial Intelligence & Data Analytics Is Essential For Your Business",
		artDate:"30 April | 1:10:34",
		artMainContent:"Organizations worldwide have been using artificial intelligence and data analytics to gain market-changing insights for years.  In this session we will define the toolsets and practices you need to embrace, why they are critical for your business, and how others have used them to transform their business.",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/Why Artificial Intelligence & Data Analytics Is Essential For Your Business.pdf",
		cookieForLead:"pdfArticleLead_10",

		relArtIconUrl1:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/forrester-8-steps-cios-must-take-to-transform-with-artificial-intelligence.pdf",
		relArtIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle1:"Forrester",
		relArtIconDecs1:"8 Steps CIOs Must Take to Transform with AI",
		relArtClicksCookie1:"clicksRelatedArticle_17",

		relArtIconUrl2:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/forbes-insights-artificially-intelligent-data-centers.pdf",
		relArtIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle2:"Third Party Report",
		relArtIconDecs2:"Forbes insights- Artificially Intelligent Data Centers-How the C-Suite Is Embracing Continuous Change to Drive Value",
		relArtClicksCookie2:"clicksRelatedArticle_18",

		relArtIconUrl3:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/practitioner-guide-to-artificial-intelligence.pdf",
		relArtIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle3:"Third Party Report",
		relArtIconDecs3:"Moor Insights - A Practitioners Guide To Artificial Intelligence",
		relArtClicksCookie3:"clicksRelatedArticle_19",

		relArtIconUrl4:"",
		relArtIconImg4:"",
		relArtIconTitle4:"",
		relArtIconDecs4:"",
		relArtClicksCookie4:"",
		
		relArtThumb1:"pdfArticle_10",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/2018/Colin-Pont.png",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:"Building the Connected Business powered by  Dell Boomi",
		relArtThumbSpeaker1:"Colin Pont",
		
		relArtThumb2:"pdfArticle_11",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Vish-Phaneendra.jpg",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:'Pivotal & Dell EMC Guide To Containers & Microservices: Future Server Platforms For "Serverless" Computing',
		relArtThumbSpeaker2:"Vish Phaneendra"
	},
	{
		articleNumber:10,
		
		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",
		
		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/2018/Colin-Pont.png",
		artSpeakerName1:"Colin Pont",
		artSpeakerDecs1:"Alliance Director APJ,<br>Dell Boomi",
		
		artSpeakerUrl2:"",
		artSpeakerName2:"Sanjiv Sinha",
		artSpeakerDecs2:"Managing Director,<br>Deloitte Consulting LLP",
		
		artCat:"Digital Transformation",
		artMainHead:"Building the Connected Business powered by  Dell Boomi",
		artDate:"30 April | 1:10:34",
		artMainContent:"We live in a multi-cloud world.  Dell Boomi can quickly and easily connect your applications and data so legacy on premise apps can interact with new Software as a Service Platforms, making your hybrid cloud solution a reality.  Dell Boomi enhances and extends the Dell Technologies Digital and IT Transformation solutions by liberating your data to be consumed by cloud native apps in new and different way, whether the data/app lives on- or off-premise.",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/Building the Connected Business powered by Dell Boomi​.pdf",
		cookieForLead:"pdfArticleLead_11",

		relArtIconUrl1:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/forrester-8-steps-cios-must-take-to-transform-with-artificial-intelligence.pdf",
		relArtIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle1:"Forrester",
		relArtIconDecs1:"8 Steps CIOs Must Take to Transform with AI",
		relArtClicksCookie1:"clicksRelatedArticle_17",

		relArtIconUrl2:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/forbes-insights-artificially-intelligent-data-centers.pdf",
		relArtIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle2:"Third Party Report",
		relArtIconDecs2:"Forbes insights- Artificially Intelligent Data Centers-How the C-Suite Is Embracing Continuous Change to Drive Value",
		relArtClicksCookie2:"clicksRelatedArticle_18",

		relArtIconUrl3:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/practitioner-guide-to-artificial-intelligence.pdf",
		relArtIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle3:"Third Party Report",
		relArtIconDecs3:"Moor Insights - A Practitioners Guide To Artificial Intelligence",
		relArtClicksCookie3:"clicksRelatedArticle_19",

		relArtIconUrl4:"",
		relArtIconImg4:"",
		relArtIconTitle4:"",
		relArtIconDecs4:"",
		relArtClicksCookie4:"",

		relArtThumb1:"pdfArticle_11",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Vish-Phaneendra.jpg",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:'Pivotal & Dell EMC Guide To Containers & Microservices: Future Server Platforms For "Serverless" Computing',
		relArtThumbSpeaker1:"Vish Phaneendra",
		
		relArtThumb2:"pdfArticle_7",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Vish-Phaneendra.jpg",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:"Introduction to Pivotal Software",
		relArtThumbSpeaker2:"Vish Phaneendra"
	},
	{
		articleNumber:11,
		
		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",
		
		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Vish-Phaneendra.jpg",
		artSpeakerName1:"Vish Phaneendra",
		artSpeakerDecs1:"Director, South Asia,<br>Pivotal",
		
		artSpeakerUrl2:"",
		artSpeakerName2:"",
		artSpeakerDecs2:"",
		
		artCat:"Digital Transformation",
		artMainHead:'Pivotal & Dell EMC Guide To Containers & Microservices: Future Server Platforms For "Serverless" Computing',
		artDate:"30 April | 1:10:34",
		artMainContent:"An overview of the technology basics of container, micro services and the supporting ecosystem. Additionally industry segment over-arching guiding principles and themes followed by a description of how Dell servers, storage and networking elements can be built to provide a solution for this new space.",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/Pivotal & Dell EMC Guide To Containers & Microservices Future Server Platforms For Serverless Computing.pdf",
		cookieForLead:"pdfArticleLead_12",

		relArtIconUrl1:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/forrester-8-steps-cios-must-take-to-transform-with-artificial-intelligence.pdf",
		relArtIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle1:"Forrester",
		relArtIconDecs1:"8 Steps CIOs Must Take to Transform with AI",
		relArtClicksCookie1:"clicksRelatedArticle_17",

		relArtIconUrl2:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/forbes-insights-artificially-intelligent-data-centers.pdf",
		relArtIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle2:"Third Party Report",
		relArtIconDecs2:"Forbes insights- Artificially Intelligent Data Centers-How the C-Suite Is Embracing Continuous Change to Drive Value",
		relArtClicksCookie2:"clicksRelatedArticle_18",

		relArtIconUrl3:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/practitioner-guide-to-artificial-intelligence.pdf",
		relArtIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle3:"Third Party Report",
		relArtIconDecs3:"Moor Insights - A Practitioners Guide To Artificial Intelligence",
		relArtClicksCookie3:"clicksRelatedArticle_19",

		relArtIconUrl4:"",
		relArtIconImg4:"",
		relArtIconTitle4:"",
		relArtIconDecs4:"",
		relArtClicksCookie4:"",
		
		relArtThumb1:"pdfArticle_7",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/Vish-Phaneendra.jpg",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:"Introduction to Pivotal Software",
		relArtThumbSpeaker1:"Vish Phaneendra",
		
		relArtThumb2:"pdfArticle_8",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"https://www.delltechnologies.com/content/dam/delltechnologies/images/forum/Andrew%20Haschka%20-Updated.jpg",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:"Building a Foundation ​for Digital Business​",
		relArtThumbSpeaker2:"Andrew Haschka"
	},
	{
		articleNumber:12,
		
		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",
		
		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/delltechnologies/images/forum/ChristopherChoong.jpg",
		artSpeakerName1:"Christopher Choong",
		artSpeakerDecs1:"Product Manager, Client Solutions Group,<br>Dell EMC Malaysia",
		
		artSpeakerUrl2:"",
		artSpeakerName2:"",
		artSpeakerDecs2:"",
		
		artCat:"Workforce Transformation",
		artMainHead:"Workforce Transformation",
		artDate:"30 April | 1:10:34",
		artMainContent:"As technology transforms the world, it is also transforming the way we work. Work is no longer a destination, it's an activity. Workers want the choice to stay connected and be productive where, when and however they need. They also have a stronger point of view on technology. To successfully navigate this workforce transformation, you need to consider both end user needs and IT needs. Upgrading your hardware solves half the issue. Organizations also have to look at upgrading how they manage, support and secure their PCs, and find more efficient, effective solutions to meet the needs of this emerging workforce. In this session, let us explain how Workforce Transformation can work for you.",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/Workforce Transformation.pdf",
		cookieForLead:"pdfArticleLead_13",

		relArtIconUrl1:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/Dell_CS-ebook_v7_11x8.5.pdf",
		relArtIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle1:"eBook",
		relArtIconDecs1:"Kickstart Your Workforce Transformation eBook",
		relArtClicksCookie1:"clicksRelatedArticle_20",
		
		relArtIconUrl2:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/redefine-your-workforce-enablement-through-productivity.pdf",
		relArtIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle2:"Third party report",
		relArtIconDecs2:"Forrester: Redefine Your Workforce Enablement Through Productivity. Over 82% of workers believe that truly customized technology to boost their productivity",
		relArtClicksCookie2:"clicksRelatedArticle_21",

		relArtIconUrl3:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/Unleash_creativity_whitepaper.pdf",
		relArtIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle3:"Brochure",
		relArtIconDecs3:"Unleash the Creative Force of Today's Workers. 20% of workers are satisfied with their technology: Read report",
		relArtClicksCookie3:"clicksRelatedArticle_22",

		relArtIconUrl4:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/the-rise-of-the-micro-pc.pdf",
		relArtIconImg4:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle4:"Third Party Report",
		relArtIconDecs4:"Forrester: The rise of Micro PC",
		relArtClicksCookie4:"clicksRelatedArticle_23",
		
		relArtThumb1:"pdfArticle_13",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/delltechnologies/images/forum/ChristopherChoong.jpg",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:"Right-size technology for the modern workforce",
		relArtThumbSpeaker1:"Christopher Choong",
		
		relArtThumb2:"pdfArticle_14",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"https://www.delltechnologies.com/content/dam/delltechnologies/images/forum/LeeSikJun.jpg",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:"Migrating to Win10? How you can deploy new PC technology with greater speed and less effort",
		relArtThumbSpeaker2:"Lee Sik Jun"
	},
	{
		articleNumber:13,
		
		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",
		
		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/delltechnologies/images/forum/ChristopherChoong.jpg",
		artSpeakerName1:"Christopher Choong",
		artSpeakerDecs1:"Product Manager, Client Solutions Group,<br>Dell EMC Malaysia",
		
		artSpeakerUrl2:"",
		artSpeakerName2:"",
		artSpeakerDecs2:"",
		
		artCat:"Workforce Transformation",
		artMainHead:"Right-size technology for the modern workforce",
		artDate:"30 April | 1:10:34",
		artMainContent:"When it comes to work technology, one size no longer fits all. Dell has invested in research to better understand how people really work and identified different types of workers (we call them personas) and the technology they need to be most productive. Whether they are in the office, at home, on the road or in the field, giving your employees the right technology for their job supports productivity, improves satisfaction, and maintains your return on investment.",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/Right-size technology for the modern workforce.pdf",
		cookieForLead:"pdfArticleLead_14",

		relArtIconUrl1:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/the-rise-of-the-micro-pc.pdf",
		relArtIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle1:"Third Party Report",
		relArtIconDecs1:"Forrester: The rise of Micro PC",
		relArtClicksCookie1:"clicksRelatedArticle_23",
		
		relArtIconUrl2:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/freedom-from-wires-article.pdf",
		relArtIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle2:"Brochure",
		relArtIconDecs2:"A World Without Wires",
		relArtClicksCookie2:"clicksRelatedArticle_24",
		
		relArtIconUrl3:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/immersive-productivity-article.pdf",
		relArtIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle3:"Brochure",
		relArtIconDecs3:"An immersive experience is as close as your screen",
		relArtClicksCookie3:"clicksRelatedArticle_25",
		
		relArtIconUrl4:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/how-to-make-your-win10-migration-painless.pdf",
		relArtIconImg4:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle4:"Brochure",
		relArtIconDecs4:"How to Make Your Win 10 Migration Painless",
		relArtClicksCookie4:"clicksRelatedArticle_26",
		
		relArtThumb1:"pdfArticle_14",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/delltechnologies/images/forum/LeeSikJun.jpg",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:"Migrating to Win10? How you can deploy new PC technology with greater speed and less effort",
		relArtThumbSpeaker1:"Lee Sik Jun",
		
		relArtThumb2:"pdfArticle_12",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"https://www.delltechnologies.com/content/dam/delltechnologies/images/forum/ChristopherChoong.jpg",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:"Workforce Transformation",
		relArtThumbSpeaker2:"Christopher Choong"
	},
	{
		articleNumber:14,
		
		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",
		
		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/delltechnologies/images/forum/LeeSikJun.jpg",
		artSpeakerName1:"Lee Sik Jun",
		artSpeakerDecs1:"Business Development Manager,<br>Dell EMC",
		
		artSpeakerUrl2:"",
		artSpeakerName2:"",
		artSpeakerDecs2:"",
		
		artCat:"Workforce Transformation",
		artMainHead:"Migrating to Win10? How you can deploy new PC technology with greater speed and less effort",
		artDate:"30 April | 1:10:34",
		artMainContent:"Migrating to Win10 promises improved performance and increased user productivity. But deploying PCs that take advantage of this powerful technology can be time consuming with tasks such as imaging, migration of user data, installation at multiple sites and, for remote users, securing the intellectual property that resides on PCs that have reached end of life. Learn how we can help you conquer the complexity of PC deployment and quickly realize the return on your investment.",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/Migrating to Win10 How you can deploy new PC technology with greater speed and less effort.pdf",
		cookieForLead:"pdfArticleLead_15",

		relArtIconUrl1:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/how-to-make-your-win10-migration-painless.pdf",
		relArtIconImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle1:"Brochure",
		relArtIconDecs1:"How to Make Your Win 10 Migration Painless",
		relArtClicksCookie1:"clicksRelatedArticle_26",
		
		relArtIconUrl2:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/Dell_CS-ebook_v7_11x8.5.pdf",
		relArtIconImg2:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle2:"eBook",
		relArtIconDecs2:"Kickstart Your Workforce Transformation eBook",
		relArtClicksCookie2:"clicksRelatedArticle_20",
		
		relArtIconUrl3:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/redefine-your-workforce-enablement-through-productivity.pdf",
		relArtIconImg3:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle3:"Third party report",
		relArtIconDecs3:"Forrester: Redefine Your Workforce Enablement Through Productivity. Over 82% of workers believe that truly customized technology to boost their productivity",
		relArtClicksCookie3:"clicksRelatedArticle_21",
		
		relArtIconUrl4:"https://www.delltechnologies.com/content/dam/delltechnologies/assets/DTF-Post-Event/Unleash_creativity_whitepaper.pdf",
		relArtIconImg4:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/Post-Event-Assets/icon44.jpg",
		relArtIconTitle4:"Brochure",
		relArtIconDecs4:"Unleash the Creative Force of Today's Workers. 20% of workers are satisfied with their technology: Read report",
		relArtClicksCookie4:"clicksRelatedArticle_22",

		relArtThumb1:"pdfArticle_12",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/delltechnologies/images/forum/ChristopherChoong.jpg",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:"Workforce Transformation",
		relArtThumbSpeaker1:"Christopher Choong",
		
		relArtThumb2:"pdfArticle_13",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"https://www.delltechnologies.com/content/dam/delltechnologies/images/forum/ChristopherChoong.jpg",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:"Right-size technology for the modern workforce",
		relArtThumbSpeaker2:"Christopher Choong"
	},	
	{
		articleNumber:15,
		
		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",
		
		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/PK-Gupta.png",
		artSpeakerName1:"PK Gupta",
		artSpeakerDecs1:"Global Presales Lead, Data Protection,<br>Dell EMC",
		
		artSpeakerUr2:"",
		artSpeakerName2:"",
		artSpeakerDecs2:"",
		
		artCat:"Security Transformation",
		artMainHead:"Cyber-Protection & Recovery - Protecting Your Business From a Destructive Cyber-Attack with RSA & Dell EMC",
		artDate:"30 April | 1:10:34",
		artMainContent:"According to analysts, 2-3 million Ransomware attacks occurred in 2016, predicted to double every year through 2019. However, most organizations' backup infrastructure was not designed to recover from a cyberattack. Dell EMC and RSA can provide a resilient infrastructure to protect and recover from a destructive cyberattack. This session will include demonstrations of automated workflows and security analytics tools.",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/Cyber-Protection & Recovery – Protecting Your Business From a Destructive Cyber-Attack with RSA & Dell EMC.pdf",
		cookieForLead:"pdfArticleLead_16",

		relArtIconUrl1:"",
		relArtIconImg1:"",
		relArtIconTitle1:"",
		relArtIconDecs1:"",
		relArtClicksCookie1:"",
		
		relArtIconUrl2:"",
		relArtIconImg2:"",
		relArtIconTitle2:"",
		relArtIconDecs2:"",
		relArtClicksCookie2:"",

		relArtIconUrl3:"",
		relArtIconImg3:"",
		relArtIconTitle3:"",
		relArtIconDecs3:"",
		relArtClicksCookie3:"",
		
		relArtIconUrl4:"",
		relArtIconImg4:"",
		relArtIconTitle4:"",
		relArtIconDecs4:"",
		relArtClicksCookie4:"",

		relArtThumb1:"pdfArticle_16",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/PK-Gupta.png",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:"GDPR: What is it, Why Do I Care and What Should I Do?",
		relArtThumbSpeaker1:"PK Gupta",
		
		relArtThumb2:"",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:"",
		relArtThumbSpeaker2:""
	},
	{
		articleNumber:16,
		
		ArtFBUrl:"https://www.facebook.com/delltechnologies/",
		ArtTwitterUrl:"https://twitter.com/delltech",
		ArtLinkedinUrl:"https://www.linkedin.com/company/delltechnologies",
		artSpeakerUrl:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/PK-Gupta.png",
		artSpeakerName1:"PK Gupta",
		artSpeakerDecs1:"Global Presales Lead, Data Protection,<br>Dell EMC",
		
		artSpeakerUrl2:"",
		artSpeakerName2:"",
		artSpeakerDecs2:"",
		
		artCat:"Security Transformation",
		artMainHead:"GDPR: What is it, Why Do I Care and What Should I Do?",
		artDate:"30 April | 1:10:34",
		artMainContent:"",
		artDownload:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/malaysia/forum/post-event-assets/GDPR What is it, Why Do I Care and What Should I Do.pdf",
		cookieForLead:"pdfArticleLead_17",

		relArtIconUrl1:"",
		relArtIconImg1:"",
		relArtIconTitle1:"",
		relArtIconDecs1:"",
		relArtClicksCookie1:"",

		relArtIconUrl2:"",
		relArtIconImg2:"",
		relArtIconTitle2:"",
		relArtIconDecs2:"",
		relArtClicksCookie2:"",
		
		relArtIconUrl3:"",
		relArtIconImg3:"",
		relArtIconTitle3:"",
		relArtIconDecs3:"",
		relArtClicksCookie3:"",
		
		relArtIconUrl4:"",
		relArtIconImg4:"",
		relArtIconTitle4:"",
		relArtIconDecs4:"",
		relArtClicksCookie4:"",
		
		relArtThumb1:"pdfArticle_15",
		relArtThumbOverlay1:"pdf-doc-content",
		relArtThumbImg1:"https://www.delltechnologies.com/content/dam/uwaem/production-design-assets/english-singapore/events/forum/2018/PK-Gupta.png",
		relArtThumbDate1:"30 April | 1:10:34",
		relArtThumbDesc1:"Cyber-Protection & Recovery – Protecting Your Business From a Destructive Cyber-Attack with RSA & Dell EMC",
		relArtThumbSpeaker1:"PK Gupta",
		
		relArtThumb2:"",
		relArtThumbOverlay2:"pdf-doc-content",
		relArtThumbImg2:"",
		relArtThumbDate2:"30 April | 1:10:34",
		relArtThumbDesc2:"",
		relArtThumbSpeaker2:""
	},		
];
